### PR TITLE
Fix hfd-service rules; it listens on the system bus

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
Don't look at the man behind the `git blame` for putting this in with `bus=session` originally...

### CODE REVIEW

**Review by dobey — APPROVED** [review]
The system is up.

**Comment by UniversalSuperBox** [comment]
For QA: Do apps like TELEports cause a vibration when you open a chat or push a button (once) on your Android9 device? If so, this is working.

**Comment by CDLProduction** [comment]
Teested on lavender currecnt rc build 2021-w08
When open chat **failed**
When push button **failed**
When receive notifications **passed**

**Comment by cibersheep** [comment]
-Telegram vibrates once when cancelling ContentHub page (E5)

**Comment by ghost** [comment]
Tested on BQ Aquaris E4.5 and RC 2021-W10:
When open chat **failed**
When push button **failed**
When receive notifications **passed**

**Pull request merged**
