### PR TITLE
Add support for new application folder (qt 5.9) 

### PR DESCRIPTION
**Pull request by mariogrip**

### CODE REVIEW

**Comment by dpniel** [comment]
I'm wondering if a better fix for this would be figuring out why [UCApplication](https://github.com/ubports/ubuntu-ui-toolkit/blob/10b0d974b1e2c042cc044b0565d7fe1a4b12209c/src/UbuntuToolkit/ucapplication.cpp#L68) isn't correctly configuring the storage location. As the `QtProject` part is usually a case of no organization being set and QtProject used as a default.

I'll just do some tests to see how the behaviour of QStandardPaths has changed in 5.9

**Comment by dpniel** [comment]
From first look i think also setting [QCoreApplication::setOrganizationName](http://doc.qt.io/qt-5/qcoreapplication.html#applicationName-prop) might resolve it. But i'll check to be sure.

**Comment by dpniel** [comment]
Ok so i can reproduce this with apps that use qmlscene and this occurs because it sets organizationName to QtProject [here](https://code.woboq.org/qt5/qtdeclarative/tools/qmlscene/main.cpp.html#515). Which will give the path of `.local/share/<orgname>/<appname>` .

If organizationName is undefined you would get `.local/share/<appname>` or if no appname you would get `.local/share/<orgname>`

I think to get the original behaviour back just setting `QCoreApplication::setOrganizationName("")` in UCApplication would be enough. See QStandardPaths outputs below

### No Org set

```
App name:  "com.ubports.name"
Org name:  ""
CacheLocation:  "/home/dan/.cache/com.ubports.name"
AppCacheLocation:  "/home/dan/.config/com.ubports.name"
ConfigLocation:  "/home/dan/.config"
CacheLocation:  "/home/dan/.cache/com.ubports.name"
DataLocation:  "/home/dan/.local/share/com.ubports.name"
AppDataLocation:  "/home/dan/.local/share/com.ubports.name"
```

### With Org Set

```
App name:  "com.ubports.name"
Org name:  "com.ubports.org"
CacheLocation:  "/home/dan/.cache/com.ubports.org/com.ubports.name"
AppCacheLocation:  "/home/dan/.config/com.ubports.org/com.ubports.name"
ConfigLocation:  "/home/dan/.config"
CacheLocation:  "/home/dan/.cache/com.ubports.org/com.ubports.name"
DataLocation:  "/home/dan/.local/share/com.ubports.org/com.ubports.name"
AppDataLocation:  "/home/dan/.local/share/com.ubports.org/com.ubports.name"
```

**Comment by dpniel** [comment]
I've created a pull request against the uitk https://github.com/ubports/ubuntu-ui-toolkit/pull/4 which I hope should resolve the issue. 

I'm concerned that this patch will create inconsistency in where apps store their data depending on how it's started. This would especially affect apps that originally started using qmlscene and switch to their own binary launcher where they would then explicitly have to define "QtProject" as the organization name (which isn't so nice).

There's also an old bug about allowing these locations https://bugs.launchpad.net/ubuntu-ui-toolkit/+bug/1197051

**Comment by mariogrip** [comment]
Ok, the other path looks good! thx! let's see how it will work out

**Comment by mariogrip** [comment]
We still seems to have some problems

```
[ 2476.466235] type=1400 audit(1519343079.298:225): apparmor="DENIED" operation="open" profile="com.ubuntu.calculator_calculator_2.2.322" name="/home/phablet/.cache/QtProject/QtQmlViewer/qmlcache/9f55b6b1da8b2cf8c7d309c68e3367b21adb36c8.qmlc" pid=23637 comm="QQmlThread" requested_mask="r" denied_mask="r" fsuid=32011 ouid=32011
```

So maybe we need this after all?

**Comment by dpniel** [comment]
Hmmm that's a weird one as the application name part of the path doesn't look like it has been set correctly for the qmlcache as it's called the app QtQmlViewer. I still don't think allowing this is the right thing to do as it looks like a configuration issue somewhere else. This change would break confinement and all apps that end up being called QtQmlViewer will be sharing the same cache directory.

Let me look into it before merging this :-)

**Comment by mariogrip** [comment]
@dpniel any status on this?

**Comment by dpniel** [comment]
@mariogrip I haven't got back to this yet. I will look into it this afternoon :-)

**Comment by dpniel** [comment]
Ok the issue here is with qmlscene again. We are now being bitten by using a prototyping tool to launch applications. :-( The main issue comes from the new qml caching we get in qt5.9 from the qml runtime which compiles qml and js resources to native code.

So from the Qt docs

> Each time you load a changed QML document, the cache is automatically re-created. Cache files are located in the same directory as the source code, if the directory is writable. Otherwise they will be placed in a sub-directory of QStandardPaths::CacheLocation with the name "qmlcache". The file extension is .qmlc for QML documents and .jsc for imported JavaScript modules.

Because of the read-only FS the cache files are tried to be placed in `QStandardPaths::CacheLocation` which as previously relies on `QCoreApplication::applicationName` and `OrganisationName` being correct to get the right location. The UITK works around this by forcing a new `applicationName` after the app has loaded. (This comes from `applicationName` property in MainView) But the issue is the qml runtime has already compiled the file containing MainView during the launch and qmlscene has set the `organisationName="QtProject"` and `applicationName="QtQmlViewer"` and is yet to get overriden by `UCApplication`.

What needs to happen is applicationName needs to be set **before** instantiating a QQmlEngine/QQuickView which isn't possible right now with qmlscene.

**Comment by dpniel** [comment]
The only thing i can think to do work around this right now is patch qmlscene to pick up the app_id off the environment and use that to set the applicationName before it loads the main qml file.

Anyone else got any thoughts?

**Comment by dpniel** [comment]
Or we could not install qmlscene in the image anymore and write a new app launcher which is a well behaving launcher for the platform that set's the world up correctly. And then just symlink qmlscene so current apps would continue to work and new apps would use the `app-launch` launcher or whatever we decide to call it?

I understand not everyone wants to worry about creating binary launchers and there is value to qmlscene being able to provide that. I just think it's probably not the right tool for production anymore

**Comment by dpniel** [comment]
Can we kill this PR now? as things seem to be good again with the qmlscene patching

**Comment by mariogrip** [comment]
Jep!

**Pull request closed without merging**
